### ISSUE TITLE
Implements stats

### ISSUE THREAD

**Issue by mikbry** [Opla/backend#27]
In Metrics controller, we need to implements real data.
From User controller/model:
- users
- sessions

From Messenger controller/model:
- conversations
- messages per conversation
- responses speed (and also from Bots ?)

From Bots controller/model:
- errors

**Comment by agardou** [comment]
@mikbry can you define exactly what is  : 
* a session : from login to logout ? or else to token expiration ?
* a conversation : how/when a conversation ends ?

**Comment by mikbry** [comment]
a session: is an exchange of messages during a lapse of time. It could start with a Hello and end with a Bye. But after a certain amount time of unactivity like 1 hour, (maybe we could have a variable to set it up) we define it closed.
a conversation: is all messages exchanged between a robot and a user
response speed : only response time

**Comment by agardou** [comment]
i've seen admin parameters plugin in opla-backend and zoapp that also give metrics (mock)
do i stay on metrics controller ? 
shall we remove this extension ? 
or i only implement metrics and do not change admin parameters extension

**Comment by mikbry** [comment]
stay in metrics controller.
admin is more general informations about the backend. in getAdminParameters it should return {} not the mockup we have actually yes.

**Comment by agardou** [comment]
for the messages per conversation metrics do we compute an average value ?

**Comment by mikbry** [comment]
yes

**Comment by agardou** [comment]
we need to define a precision to error rate number, do we include this front update in this issue ?

**Comment by mikbry** [comment]
ok

**Comment by agardou** [comment]
cf https://github.com/Opla/backend/issues/41#issuecomment-376940397

@mikbry how do i filter conversations ? i can list bot(s) with current user as author (could multiple bots have same author ?) and restrict metrics to all conversations which bot(s) participating ?

**Comment by mikbry** [comment]
getConversations({ id: bot.id }); should return all conversations for a bot, as bot is a participant in conversations.

**Comment by agardou** [comment]
ok and for the bots questions ? which bots are supposed to be taken in consideration ? first bot with user as author ?

**Comment by mikbry** [comment]
yes first bot with user as author. Multi-bots won't be supported officially on CE version.

**Comment by mikbry** [comment]
yes messengerModel
