### ISSUE TITLE
Impossible to create a new user on a fresh install

### ISSUE THREAD

**Issue by lunika** [Opla/backend#39]
On a fresh install, I can't create a new user. I follow all the instructions to install both front and back applications. 
I use the backend with docker-compose

Here the log I have : 

```
2018-03-28T08:26:31.769Z - info: Start Opla.ai 0.9.0
2018-03-28T08:26:31.775Z - info: will init
2018-03-28T08:26:31.775Z - info: initMiddlewares
2018-03-28T08:26:38.638Z - info: OpenNLX onDispatch:  bot updateBot
2018-03-28T08:26:38.651Z - info: Undefined user Id
2018-03-28T08:26:38.659Z - info: data.intents id=2, name=HelloWorld
```

**Comment by willdurand** [comment]
do you have issues on the frontend?

**Comment by lunika** [comment]
No, nothing in the front application.

I'm on the `/create` endpoint in the frontend application and I fill the form with the template, assistant name, username, password and language.

I am on firefox and I just test it on chrome and it works. So I'm not sure if it's a frontend issue.

**Comment by mikbry** [comment]
If it works on Chrome, sounds like a front issue on Firefox ?

**Comment by lunika** [comment]
So it's not a browser issue. The issue was a too short password... The minimum length is 4 characters and I put only 3.

**Comment by mikbry** [comment]
Ah ok an issue in frontend with parameters validation

**Comment by lunika** [comment]
yes and also in back because we have no information in the response explaining why there is an error

**Comment by willdurand** [comment]
ah f*** right! we do not have error handling here. It does the same thing if you enter an invalid or already used email address 😕

**Comment by lunika** [comment]
I think this issue can be closed while this pr is merged https://github.com/Opla/front/pull/68
