### ISSUE TITLE
metrics endpoint shape

### ISSUE THREAD

**Issue by agardou** [Opla/backend#41]
metric endpoint shape is currently :
> {
> "users":{"count":3},
> "conversations":{"count":2,"messages_per_conversation":3},
> "sessions":{"duration":15210},
> "errors":{"rate":0.33},
> "responses":{"speed":25}
> } 

could be reshaped with grouping similar metrics, like   : 
> {
> "users":{"count":3},
> "conversations": {"count":2, "messages_per_conversation":3, "duration":15210},
> "bots": {  "error_rate":0.33, "response_speed":25 } 
> }

**Comment by willdurand** [comment]
> There is one bot per metric endpoint

does that mean the URI should look like `/metrics/<botId>`?

**Comment by mikbry** [comment]
yes that's right

**Comment by agardou** [comment]
does that implies that this metrics endpoint must not read all datafor this instance  ? metrics from https://github.com/Opla/backend/pull/33 count all users/conversations/messages in DB

**Comment by mikbry** [comment]
yes only users/conversations/message per bot
