### ISSUE TITLE
Imported intents are not used by OpenNLX

### ISSUE THREAD

**Issue by mikbry** [Opla/backend#42]
When:
- Create a chatbot with imported json data exported from another chatbot.
- Intents are listed and ok
- Use the playground and test an intent
What:
- The chatbot don't respond and display the error box to create a new intent
Expected:
- The chatbot should respond using associated intent

Could be a problem in OpenNLX, need to isolate where the bug occurs.

**Comment by mikbry** [comment]
In logs I got:
putIntents not same version:  null
It could be the cause of the bug

**Comment by lunika** [comment]
This an update how to reproduce the problem : 

- create a new bot (empty or not)
- add new intents if you choose an empty.
- play with the playground  and you will always have the error message saying to create an intent
- kill the backenf server
- restart it
- it works

**Comment by lunika** [comment]
new update : 

once an account created and you log in, openNLX seems not able to retrieve the intent provider so when you add new intents, nothing is set into openNLX

**Comment by lunika** [comment]
once new bot created, an agent is not set in opennlx, this is why openNLX has no intent provider registered
