### ISSUE TITLE
Metrics: session duration is invalid

### ISSUE THREAD

**Issue by willdurand** [Opla/backend#44]
It looks like the session duration returned in the API is not valid with a fresh database:

<img width="395" alt="screen shot 2018-04-08 at 22 24 54" src="https://user-images.githubusercontent.com/217628/38472152-bc990522-3b7b-11e8-8706-9383109bead5.png">

**Comment by mikbry** [comment]
Session duration is still invalid:
![screen shot 2018-05-21 at 10 52 01](https://user-images.githubusercontent.com/395718/40298930-01de4fd6-5ce5-11e8-951c-a63c71d4a3eb.png)

**Comment by lodelestra** [comment]
also, I had trouble figuring out how to define a session duration.
Should it be the time between chat creation and last message or the time between the first and the last message ?
Now it's the time between the chat creation and the last message. So if you open a page with the chat and one hour later send "hello" it's a 3600000ms session

**Comment by mikbry** [comment]
We should define a timeout between two messages. If the timeout is reach then we decide it is a new conversation. Let's start with a 10min timeout
